### ISSUE TITLE
More detailed console logs

### ISSUE THREAD

**Issue by vicho001** [medizininformatik-initiative/INTERPOLAR#181]
Hey, i am from the DIZ in Essen and i tried to run the docker compose but i get this error message:
`Download of 1st Set of Bundles for 3 IDs (FHIR Resource: Location )
Getting Bundles via POST failed. Try to get them via GET.
Bundles for the following IDs could not be downloaded:c("Patient/123)`

I suspect that it has something to do with our FHIR server, which is developed by us. How can i see the FHIR-Requests that are being executed? Is there a parameter for that?

**Comment by Flow191** [comment]
Hey, the error with the download of the location resource was already known and has already been fixed. We have also improved the logging so that the FHIR requests used are now logged in "outputLocal/kds2db/bundles". In order to test the current changes, the following release tag (v0.1.1) must be checked out with "git checkout tags/v0.1.1". Please let us know if there are any further errors.

**Comment by vicho001** [comment]
Ich habe den neuen release-tag ausgecheckt und ausführt, jedoch kam es zum selben Fehler. Der Ordner "outputLocal/" ist leer. Hier habe ich die Ausgaben
[IP-ausgabeError.txt](https://github.com/medizininformatik-initiative/INTERPOLAR/files/15322598/IP-ausgabeError.txt)

**Comment by Flow191** [comment]
Wir sind gerade an einen Entwicklungsstand, wo sich die Datenbank von dem kds2db Modul etwas unterscheidet. Die von der Datenbank erwarteten Datenstruktur ist anders als die FHIR-Daten die wir dort rein schreiben möchten. Wir sind gerade dabei daran zu arbeiten. Spätestes zum nächsten Release in ca. 2 Wochen sollte diese Feher nicht mehr bestehen.

**Comment by Flow191** [comment]
Hallo, der aufgetretende Fehler sollte im aktuellen Release v0.2.2 behoben sein. Ich schließe dieses Issue, falls der Fehler weiterhin besteht, kann das Issue wieder geöffnet werden.
